/**
 * Designed, programmed and tested by 
 * Renzo Nahuel Murina Cadierno (a.k.a) "Max".
 * Contact: nmcadierno@hotmail.com
 * GIT: github.com/RenzoMurinaCadierno
 * 
 * Disclaimer:
 * 
 * Before writing the very first line of this whole app, my intention was 
 * to make it open source, so you can use it in any way you wish. 
 * 
 * But please, it would be much appreciated if you could give the
 * credits to the author and the links of contact and of download to the
 * original work, as I'm trying my best to be acknowledged to safely drop
 * the not-life-fulfilling job I'm currently at, and finally dedicate my
 * life to my true passion: coding apps and applets.
 * 
 * Additional commentary:
 * 
 * The code in this class was written by hand, and that is why the GUI's 
 * aesthetic is not at all appealing.
 * I did it this as a practical exercise to understand how a JForm is 
 * created from scratch and give it my best shot, since this whole 
 * project is my first attempt at coding in Java and at OOP.
 * I'm new to programming. I have been studying Java, Javascript and Python
 * (and some of its frameworks) for half a year since this date.
 */
package Doughnut;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 * This class represents the "final results" GUI.
 * <p>
 * > The Letter button wheel from the associated DoughnutGame's instance is 
 * replicated here.<br>
 * > By clicking on each button, the finalItem object linked to it are be
 * displayed on screen so that the user can check the Letter, condition,
 * question, real answer, answer given while in game and the status.<br>
 * > The amount of correct, incorrect, passed and unanswered questions are
 * shown on the form, as well as the final score.<br>
 * > Options to play a new game or to exit are offered to the user.<br>
 * @author
 * Renzo Nahuel Murina Cadierno (a.k.a) "Max"
 * mail: nmcadierno@hotmail.com
 */
public class GameOver extends javax.swing.JFrame {
    
    List<JButton> finalButtons;
    List<FinalItem> finalItemList = DoughnutGame.getFinalItems();

    public GameOver() {
        
        initComponents();
        
        setTitle(": : And your results are... : :");
        getContentPane().setBackground(new Color(0, 0, 51));
        this.setLocationRelativeTo(null);
        
        displayButtonText();
    
        displayScore();
        
        DoughnutGame.clearItemListAndFinalItemList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblScore = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        lblCondition = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        lblAnswerGiven = new javax.swing.JLabel();
        lblAnswer = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblLetter = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnPlayAgain = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblWrong = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblPassed = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblUnanswered = new javax.swing.JLabel();
        lblAnswerGivenFixed = new javax.swing.JLabel();
        lblAnswerFixed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScore.setBackground(new java.awt.Color(0, 0, 51));
        lblScore.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 70, 40));

        btn1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn1.setText("A");
        btn1.setNextFocusableComponent(btn2);
        btn1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn1FocusGained(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 50, 50));

        btn2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn2.setText("A");
        btn2.setNextFocusableComponent(btn3);
        btn2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn2FocusGained(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 50, 50));

        btn3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn3.setText("A");
        btn3.setNextFocusableComponent(btn4);
        btn3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn3FocusGained(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 50, 50));

        btn4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn4.setText("A");
        btn4.setNextFocusableComponent(btn5);
        btn4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn4FocusGained(evt);
            }
        });
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 50, 50));

        btn5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn5.setText("A");
        btn5.setNextFocusableComponent(btn6);
        btn5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn5FocusGained(evt);
            }
        });
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 50, 50));

        btn6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn6.setText("A");
        btn6.setNextFocusableComponent(btn7);
        btn6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn6FocusGained(evt);
            }
        });
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 50, 50));

        btn7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn7.setText("A");
        btn7.setNextFocusableComponent(btn8);
        btn7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn7FocusGained(evt);
            }
        });
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 50, 50));

        btn8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn8.setText("A");
        btn8.setNextFocusableComponent(btn9);
        btn8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn8FocusGained(evt);
            }
        });
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, 50));

        btn9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn9.setText("A");
        btn9.setNextFocusableComponent(btn10);
        btn9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn9FocusGained(evt);
            }
        });
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 50, 50));

        btn10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn10.setText("A");
        btn10.setMaximumSize(new java.awt.Dimension(50, 50));
        btn10.setMinimumSize(new java.awt.Dimension(50, 50));
        btn10.setNextFocusableComponent(btn1);
        btn10.setPreferredSize(new java.awt.Dimension(50, 50));
        btn10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn10FocusGained(evt);
            }
        });
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 50));

        lblCondition.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lblCondition.setForeground(new java.awt.Color(255, 255, 255));
        lblCondition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 30));

        lblQuestion.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 230, 80));

        lblAnswerGiven.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lblAnswerGiven.setForeground(new java.awt.Color(255, 255, 255));
        lblAnswerGiven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblAnswerGiven, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 230, 20));

        lblAnswer.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lblAnswer.setForeground(new java.awt.Color(255, 255, 255));
        lblAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 230, 20));

        lblStatus.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 110, 40));

        lblLetter.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblLetter.setForeground(new java.awt.Color(255, 255, 255));
        lblLetter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLetter.setToolTipText("");
        getContentPane().add(lblLetter, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 50, 30));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Game Over!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Final Score");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 110, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<html><div style='text-align: center;'>Click on the buttons or navigate through them with TAB to check the questions, its answers and your given answers.</div></html>");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, 150));

        btnPlayAgain.setFont(new java.awt.Font("Verdana", 2, 13)); // NOI18N
        btnPlayAgain.setText("Play again");
        btnPlayAgain.setNextFocusableComponent(btnExit);
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlayAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 110, 40));

        btnExit.setFont(new java.awt.Font("Verdana", 2, 13)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setNextFocusableComponent(btn1);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 110, 40));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Wrong :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 60, 50));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Correct :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 70, 50));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Passed :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 60, 50));

        lblWrong.setBackground(new java.awt.Color(0, 0, 51));
        lblWrong.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lblWrong.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblWrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 20, 50));

        lblCorrect.setBackground(new java.awt.Color(0, 0, 51));
        lblCorrect.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lblCorrect.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblCorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 20, 50));

        lblPassed.setBackground(new java.awt.Color(0, 0, 51));
        lblPassed.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lblPassed.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblPassed, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 20, 50));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Unanswered :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 100, 50));

        lblUnanswered.setBackground(new java.awt.Color(0, 0, 51));
        lblUnanswered.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lblUnanswered.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblUnanswered, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 20, 50));

        lblAnswerGivenFixed.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAnswerGivenFixed.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblAnswerGivenFixed, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 110, 30));

        lblAnswerFixed.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAnswerFixed.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblAnswerFixed, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 60, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        /**
     * Sets the buttons' text to their respective Letters.
     */
    private void displayButtonText() {
        
        finalButtons = new ArrayList();
        
        finalButtons.add(btn1); finalButtons.add(btn2);
        finalButtons.add(btn3); finalButtons.add(btn4); 
        finalButtons.add(btn5); finalButtons.add(btn6); 
        finalButtons.add(btn7); finalButtons.add(btn8);
        finalButtons.add(btn9); finalButtons.add(btn10);
        
        finalButtons.forEach(item ->{
            item.setText(finalItemList
                            .get(finalButtons.indexOf(item))
                            .getLetter());
        });
    }
    
    /**
     * Sets each JLabel text with the FinalItem object values
     * assigned to the corresponding JButton of the doughnut wheel.
     * @param buttonNumber 
     * The int for the button number value of the doughnut wheel, which 
     * will be used to get the finalItemList's objects' values and fill 
     * the JLabels with the information stored in them.
     */
    private void displayFinalItemObjectValues(int buttonNumber) {
        
        /* if we haven't clicked on any button yet and we do so now, then
           the fixed text in the JLabels title will appear to stay. */
        if(lblAnswerFixed.getText().equals("")) {
            
            lblAnswerFixed.setText("Answer");
            lblAnswerGivenFixed.setText("Given Answer");
        }
        
        /* we set the text on each JLabel for each attribute of the 
           finalItemList object in the buttonNumber position.
           We convert the Question, Answer and Given Answer to the
           spanish characters (if any), so that they do not look
           like a garbled mess. */
        lblCondition.setText(finalItemList.get(buttonNumber).getCondition());
        
        lblLetter.setText(finalItemList.get(buttonNumber).getLetter());
        
        lblQuestion.setText(
                  "<html><div style='text-align: center;'>"
                + Util.convertToSpanishCharacters(
                        finalItemList.get(buttonNumber).getQuestion())
                + "</div></html>");
        
        lblAnswer.setText(
                Util.convertToSpanishCharacters(
                finalItemList.get(buttonNumber).getAnswer()));
        
        lblAnswerGiven.setText(
                Util.convertToSpanishCharacters(
                finalItemList.get(buttonNumber).getAnswerGiven().trim()));
        
        /* and set the Status condition as a text to lblStatus JLabel,
           depending on the finalItemList's object value for the button */
        switch (finalItemList.get(buttonNumber).getStatus()) {
            
            case 0: //set status unanswered and pass, then center everything!
                lblStatus.setForeground(Color.blue);
                lblStatus.setText("Unanswered");  
                break;
                
            case 3:
                lblStatus.setForeground(Color.yellow);
                lblStatus.setText("Passed");  
                break;
                
            case 1:
                lblStatus.setForeground(Color.green);
                lblStatus.setText("Correct!");    
                break;
                
            case 2:
                lblStatus.setForeground(Color.red);
                lblStatus.setText("Wrong");
                break;
                
            default:
                break;
        }
    }  
    
    /**
     * Displays the final score and the individual ones for the 
     * correct, wrong and unanswered answers on each assigned
     * JLabel.
     * <p>
     * This method also paints the foreground color of the JLabels
     * assigned to the scores according to the obtained values, and
     * sets focus on the "Play Again" button.
     */
    private void displayScore() {
        
        int correct = 0;
        int wrong = 0;
        int passed = 0;
        int unanswered = 0;
        
        //we increase the respective counter depending on the object's status.
        for (int i = 0; i < finalItemList.size(); i++) {
           
            switch (finalItemList.get(i).getStatus()) {
                
                case 0:
                    unanswered++;
                    finalButtons.get(i).setBackground(Color.blue);
                    finalButtons.get(i).setForeground(Color.white);
                    break;
                
                case 1:
                    correct++;
                    finalButtons.get(i).setBackground(Color.green);
                    break;
                
                case 2:
                    wrong++;
                    finalButtons.get(i).setBackground(Color.red);
                    break;
                           
                case 3:
                    passed++;
                    finalButtons.get(i).setBackground(Color.yellow);
                    break;
                    
                default:
                    break;
            }
        }
        
        //we set the label's text to the counter values.
        lblCorrect.setText(String.valueOf(correct));
        lblWrong.setText(String.valueOf(wrong));
        lblPassed.setText(String.valueOf(passed));
        lblUnanswered.setText(String.valueOf(unanswered));
        lblScore.setText(String.valueOf(correct*10 + "%"));
        
        //we apply the corresponding format depending on the values.
        Util.setFontStyleSizeColor("Calibri", 2, 18, Color.green, lblCorrect);
        Util.setFontStyleSizeColor("Calibri", 2, 18, Color.red, lblWrong);
        Util.setFontStyleSizeColor("Calibri", 2, 18, Color.yellow, lblPassed);
        Util.setFontStyleSizeColor("Calibri", 2, 18, Color.blue, lblUnanswered);

        switch (correct) {
            
            case 0:
            case 1:
            case 2:
            case 3:
                lblScore.setForeground(Color.red);
                break;
                
            case 4:
            case 5:
            case 6:
                lblScore.setForeground(Color.yellow);
                break;
                
            case 7:
            case 8:
            case 9:
            case 10:
                lblScore.setForeground(Color.green);
                break;
        }

        //and we request focus on btnPlayAgain.
        btnPlayAgain.requestFocus();
    }
    
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        if(JOptionPane.showConfirmDialog(
                        this, 
                        "Are you sure you want to leave?\n"
                      + "If so, thanks for playing!",
                        "Leaving so soon? :c",
                        JOptionPane.YES_NO_OPTION) == 0)

            System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed

        this.setVisible(false);
        this.setEnabled(false);
        
        /* we instantiate and initialize a new DoughnutMain object, starting 
           a new game up. */
        DoughnutMain rMain = new DoughnutMain();
        rMain.setVisible(true);
   
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        displayFinalItemObjectValues(0);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        displayFinalItemObjectValues(1);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        displayFinalItemObjectValues(2);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        displayFinalItemObjectValues(3);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        displayFinalItemObjectValues(4);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        displayFinalItemObjectValues(5);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        displayFinalItemObjectValues(6);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        displayFinalItemObjectValues(7);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        displayFinalItemObjectValues(8);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        displayFinalItemObjectValues(9);
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn1FocusGained
        displayFinalItemObjectValues(0);
    }//GEN-LAST:event_btn1FocusGained

    private void btn2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn2FocusGained
        displayFinalItemObjectValues(1);       
    }//GEN-LAST:event_btn2FocusGained

    private void btn3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn3FocusGained
        displayFinalItemObjectValues(2);       
    }//GEN-LAST:event_btn3FocusGained

    private void btn4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn4FocusGained
        displayFinalItemObjectValues(3);
    }//GEN-LAST:event_btn4FocusGained

    private void btn5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn5FocusGained
        displayFinalItemObjectValues(4);
    }//GEN-LAST:event_btn5FocusGained

    private void btn6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn6FocusGained
        displayFinalItemObjectValues(5);
    }//GEN-LAST:event_btn6FocusGained

    private void btn7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn7FocusGained
        displayFinalItemObjectValues(6);
    }//GEN-LAST:event_btn7FocusGained

    private void btn8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn8FocusGained
        displayFinalItemObjectValues(7);
    }//GEN-LAST:event_btn8FocusGained

    private void btn9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn9FocusGained
        displayFinalItemObjectValues(8);
    }//GEN-LAST:event_btn9FocusGained

    private void btn10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn10FocusGained
        displayFinalItemObjectValues(9);
    }//GEN-LAST:event_btn10FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblAnswerFixed;
    private javax.swing.JLabel lblAnswerGiven;
    private javax.swing.JLabel lblAnswerGivenFixed;
    private javax.swing.JLabel lblCondition;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblLetter;
    private javax.swing.JLabel lblPassed;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUnanswered;
    private javax.swing.JLabel lblWrong;
    // End of variables declaration//GEN-END:variables
}
